version: '3.4'

services:
  ecommerce.admin.httpapi.host:
    image: ${DOCKER_REGISTRY-}ecommerceadminhttpapihost
    build:
      context: .
      dockerfile: src/Ecommerce.Admin.HttpApi.Host/Dockerfile

  ecommerce.authserver:
    image: ${DOCKER_REGISTRY-}ecommerceauthserver
    build:
      context: .
      dockerfile: src/Ecommerce.AuthServer/Dockerfile


  ecommerce.public.httpapi.host:
    image: ${DOCKER_REGISTRY-}ecommercepublichttpapihost
    build:
      context: .
      dockerfile: src/Ecommerce.Public.HttpApi.Host/Dockerfile

